// import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import classNames from "classnames/bind";
import styles from "./layout.module.scss";
import Link from "next/link";
import Image from "next/image";
import PlusBtn from "@/components/common/PlusBtn";

const cx = classNames.bind(styles);

const nexonGothic = localFont({
  src: "./fonts/NEXON Lv1 Gothic OTF.woff",
  variable: "--font-nexon-gothic",
  weight: "400 500 700",
});

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${nexonGothic.variable}`}>
        <div className={cx("container")}>
          <header>
            <Link href={"/"}>
              <Image
                src={"/img/icon/logo.png"}
                alt="Project-at"
                width={40}
                height={40}
              />
              <span>
                <b>P</b>roject <b>A</b>t
              </span>
            </Link>

            <div className={"btn__container"}>
              <PlusBtn />
              <button className={"btn"}>My</button>
              <button className={"btn"}>로그인</button>
            </div>
          </header>

          <main>{children}</main>

          <footer></footer>
        </div>
      </body>
    </html>
  );
}
